### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by COMOSTER** [lynxlynxlynx/gemrb-mods#1]
I try to run mod
first error was in 5 string LANGUAGE ~English~ ~english~ ~tra/english.tra~
i delete this string
second error in 7 string
VERSION @0
i delete this string
next error 50-52 strings
  REPLACE ~PLACEHOLDER_1~ @1
  REPLACE ~PLACEHOLDER_2~ @2
  REPLACE ~PLACEHOLDER_3~ @3
i delete all this string and install complete.
when i run the game , i did't see a new multi class.
Is there a way to run correctly this mod ?

**Comment by lynxlynxlynx** [comment]
what weidu version and game type are you using? What mod did you try to install?

**Comment by COMOSTER** [comment]
weidu last version, i try on BG2 EE , BG Trilogy and BG BiG World Project. mod sorcerer-monk-cleric

**Comment by lynxlynxlynx** [comment]
Well, it can't work on bgee or bg2ee, so if you tried bgt or big world for those, that explains it.

**Comment by njunju** [comment]
Same issue, i get a Parse error at LANGUAGE

but i'm using bg2 from gog, not the enhanced edition, with bgt and installed, latest WeiDu. and mod sorcerer-monk-cleric. Can it work there?.

**Comment by lynxlynxlynx** [comment]
Try with an older Weidu, this could be due to the changes needed for bgee multilingualisation improvements.

**Comment by njunju** [comment]
the only thing that changed was Parse error (state 816) at LANGUAGE.The "state xxx" xxx just kept going lower with different versions of WeiDU. Down to state 654 at WeiDU 210. I tried using Weidu 236,230,220,210

**Comment by njunju** [comment]
Are the game tables (alignment, xpcap, weapprof, profs, 25stweap) all supposed to be in override, or should they be in data?

**Comment by njunju** [comment]
got it to install by changing BEGIN ~xxxx~ to BEGIN @0 and by moving the unhardcoded tables to override....

but when I started the game the character only has sorcerer and monk for classes but I did have spell slots in the divine spellbook but no spells. also I can't cast any sorcerer spells cause I always have 0 spells even after resting

**Comment by lynxlynxlynx** [comment]
Ok, the language issues have finally been fixed. Sorry for this not being a priority. You can now check the 10pp mod that was finished in the meanwhile (for larger than 6 player parties).
