### ISSUE TITLE
16 Party Size?

### ISSUE THREAD

**Issue by WithinAmnesia** [lynxlynxlynx/gemrb-mods#13]
https://github.com/lynxlynxlynx/gemrb-mods/tree/master/10pp#readme
"Caveats:

    scripting wise, up to 10 member parties are supported (Player10/Player10Fill objects)
        easily extended, if there's enough interest..."

I hope I can share and inspire enough interest in 16 Party Size for GemRB for the Baldur's Gate / Icewind Dale series.

I am undergoing making a 16 Party Size A.R.P.G. for Godot 4 (https://github.com/WithinAmnesia/ARPG) pre-alpha stages (not much to see other than assets but I have been doing foundational work and I got procedural generation working as a first step recently). I have an interest in testing if the old BG series can be upgraded to something like D2R+ or if it will be stuck kinda semi-niche and dated. I have been working on / with 4-8K with Diablo 2-esque (also BG / Zelda themes kinda) open source Flare Engine https://github.com/flareteam/flare-game/discussions/935 ). I was able to work bit by bit (with a lot of help from @dorkster / Justin Jacobs) to get Flare from 32-bit to 64-bit to handle 4K and even 8K graphics up from very small pixelated 90's 2000's isometric graphics. I had to rerender and remodel and create new animations to remaster and expand the Flare animations into 4K and even 8K; yet at great cost of trial and error for myself (I am not an amazing 3D modeller or coder by any means just lots of passion hopefully).

So I am wondering if old BG / IWD / BGT / 'greater old BG' can be a reasonable idea to pursue; as in to have 16 party size also (about the human limit like with Chess which is an about ~1,000+ year old near-perfected tactical RPG). Beamdog is basically disbanded and I am left to figure out if I should do more old BG work (I have about 3-5 of expansions / 2-3 games worth of un-release *very unpolished* but substantial amount of content with the old BG / IWD series). So I am not interested in making mods and mods I want to go further beyond and see if its technically feasible to do a 4K or even 8K remaster of old bg / iwd and to expand the engine and the series also. One feature I am developing with my own work is 16 party size. I don't want to be restricted to 90's technology and I want to work with 16 party size and with 16:9 aspect ratio and 4K to 8K graphics+. We have AI remastering its only getting better we can remodel like with D2R+ there are options to make the graphics better but its the party size limit. 6 Is too small now if old BG and IWD are completely and comprehensively unified and thus expanded upon like in BGT. As its just kinda boring with 6 party members when there are so many amazing Non-Player Characters to choose from; hell even 1998 BG 6 was kinda not enough with that roster let alone double or triple that with a combined roster from all the old BG / IWD realms of potential adventures. I hope GemRB can upgrade and expand upon the old BG / IWD engine much like in the theme of BGT but with better graphical support of 4K to 8K remastered 16:9 graphics and 16 Party Size. Is this feasible? Can 16 Party Size in GemRB be reasonably implemented?

**Comment by lynxlynxlynx** [comment]
Like the docs say, the mod is trivially extensible to bigger sizes. One might create timing bugs in the game scripts, but that's something that can only be easily discovered through testing. 6 was not a screen size limit, but a game design one.

You're forgetting how much micromanagement these games require. With increasing party sizes it only gets worse. Also balance is thrown out of the window without using some extra xp downscaling. At 16 that would mean much lower level caps.

But, it's open source, so feel free to shot yourself in the foot.

**Comment by lynxlynxlynx** [comment]
As for ai upscaling, quite some work has been done on that in the community as well, with even some support in NI to make it easier. It gets big fast though. And would definitely require quite some changes in the engine due all the implicit and explicit distances and calculations.

**Comment by WithinAmnesia** [comment]
Thank you for the thoughtful correspondence. I am glad that 16 Party Size sounds to be very achievable technically and yes I agree the game balance and game design overall experience / progression flow would need a comprehensive top to bottom remaster / overhaul / rework; yet I feel it could be done with careful iterative work. ToB and late SoA have big monty haul / very generous experience and overall rewards as compared to the previous chapters and areas. If one were to combine / unify the progression / overall game experience like BGT as a grand plan / 'greater old bg / iwd series' as in with everything on the table all at once type of thing, 16 Party size could be smoothed out. As to note though game balance as you astutely pointed out I agree scales along with encounter size and there would be required scaling of these kinds of experiences and what would need fair adjusting where it hopefully makes sense. If one were to go from a 6 party scaled game directly to 16 the player power went from ~6/16=0.375 or ~37.5% the size compared to a 16 party size not including zerg rushing or overwhelming fire or very powerful mass tactics and otherwise not traditionally used enmasse class combinations. 16 party size up from 6 (6->16) is at least like expanding the player power by 16/6=2.67+ times. So the world and encounters would need to scale up to at least ~2.67 and or ~3+ (~3.210) times as well in order to have some hopefully fair assemblance of balance as a starting point.

The hobgoblins and gnolls could feel more like an army too whereas I have read in the source material / nerdy Faerun lore they are sorta supported to be found in big groups or like even armies and like that's kinda cool I think fighting a small army with a pretty big but also smallish party. SoD tried to do the army / large battle experience which was okay its more a success than not hopefully at least 2/3 in pulling that epic-ish scale of combat in the old bg / bgt series. I feel with the legions of hell / avernus and other larger scale encounters like big battles / sieges (mount and blade and or total war, warcraft 1-3 etc.) MMORPG style epic raids (vanilla / classic wow - wotlk or even classic eq / project 1999 10-40-100+ person content / events) could be do-able / '~spiritually ported' to the old bg / iwd / 'greater old bg / iwd series'. The top down isometric perspective can be used to run large scale battles effectively and now with screen resolutions and the ability to pull the camera back to see pretty much the entire map it feels as though the sky is the limit or hopefully even beyond.

The AI resolution enhancing and the graphical remastering to ~4K to 8K would need a lot of heavy lifting but I am glad it is realistically do-able. Perhaps realistically the old bg / iwd area images would need to be taken out upscaled with AI and probably human remastering working together with GemRB trying to bring it all technically together across today's many 1K, 2K, 4K, 8K, 16K etc+ ~16:9 gaming platforms. 4K to 8K is about the human eye limit and even at 4K with the eye right close to the screen its hard to see individual pixels and it feels as if there are not pixels at all. At rock steady solid 60fps games feel very smooth and at 90 or 120+ fps the games are as smooth as butter I find at least and so I hear many other people also share these feelings of graphical experiences. So 4K 60fps Old BG / IWD / BGT / 'greater old bg / iwd' would be a tremendous thumping success and especially if the animation sprites were able to be remastered to ~4K to 8K for that is sort of the heart of 90% of the players experience is looking at their party and fighting / interacting / exploring other creatures along side game world back drops and gui / inventory / item visual experiences too. I feel that the old BG / IWD series has enough 32x32 and 64x64 pixel resolution assets that new assets could be faithfully remastered. As in much like with D2R and perhaps as a start with a much more reasonable scale / work load of a hobbyist community in production resources AI upscaling frame by frame of animations and areas and items; to hopefully get closer to a true 4K to 8K full graphical remaster made predominately by hand and by masters of the art. I was able to produce 4K and 8K+ resolution remastered complete visual assets like animations tilesets effects gui items abilities etc for Flare that had (I think 480p resolution) type graphics to start; much like Diablo 1 and Diablo 2 very much 32 bit graphics for sure pixelated that looked very 90's 2000's era. Yet the ~4K to 8K+ graphical remastering can be (with a lot of work and due diligence) brought up to 2020's+ ~4K to 8K+ graphical expectations and hopefully inspire a sense of wonder.

I am glad that GemRB and such a robust community supports all the work that goes into such a colossal undertaking. How long has GemRB been under development to get to this point of technology maturity / raw power like early 2000's? I think 2003 or 2004 I think, or has it been from the lat 90's and as soon as old BG1 was released? Either way its like ~20 years or ~2 decades of work that went into such an amazing software and technological feat for what must be a limited handful of very talented and very passionate people keeping the big dream alive and thriving. I am very glad that there is a future with the infinite engine style games and that this open source passionate community made a bright future for the old BG / IWD series. I sincerely hope to find a way to bring the Old BG / IWD series / BGT / 'Greater Old BG / IWD series' to a wonderful experience that stands the test of time. As with graphics that challenge human perception that nigh-transcends pixels and animation so smooth the human eye feels such experiences it witnesses are animated seamlessly smooth and realistically life like; and feel genuinely alive with a grand epic scale of combat and explorations and wonder that dares even the mental capabilities of the human experience.

Thank you for your time and feedback. I feel that Old BG / IWD realms of adventures / sagas / series can have a lot of life put into them and that they can reach that 2020's 2030's and beyond timeless legacy that all generations can enjoy. As just like in with the original 1,000+ year old tactical RPG Chess and sports, some things can live forever just as with the sense of wonder, danger and mystery within the human experience. I suppose MMO / multiplayer VR old BG / IWD would be the only thing to top / outdo the ~4K to 8K+ 60 to 120+ fps Old BG / IWD / BGT / 'Greater Old BG / IWD Complete Remastered Unified Series'. I hope likes of Old BG / IWD can be brought up the glory of BG3 one day and perhaps even beyond.

Yet bit by bit, piece by piece big things are all made up of a bunch of small things all put together hopefully greater than the sum of its parts. Just like Rome these things were / are not built in a day or short run; nor with one set of hands. Yet these works of wonder were built by many hands over many long spans of time all working together towards hopefully noble aims.

**Comment by lynxlynxlynx** [comment]
Phew, you are a verbose one. Anyway, if you end up doing something, do let us know if you hit any snags. Discord is a good choice, so the wider g3 community can weigh in.

**Comment by cygarniczka** [comment]
I played BGT with 10 party size. The experience barley fended off the annoyance of getting stuck in closed spaces. Just barely. Mods that add extended banter between NPCs saved the day - the party felt alive and interactive with each other. I think any party larger than 10 will just make you to downsize the party even if you are allowed more than 10 party people. Given you install mods that add extra items and more than 10 people to manage your 50% time of gameplay or more will be the item micromanagement which will make you drop out from the game sooner than later.
