### ISSUE TITLE
G3 links in 10pp readme outdated

### ISSUE THREAD

**Issue by Gitjas** [lynxlynxlynx/gemrb-mods#8]
Hi, the links to G3 in the 10pp readme need to be updated:
outdated link: https://www.gibberlings3.net/forums/index.php?showtopic=27138
current link: https://www.gibberlings3.net/forums/topic/27138-heard-you-like-parties/

The other one I am still searching:
outdated link: https://www.gibberlings3.net/forums/index.php?showtopic=27535

Cheers!

**Comment by Gitjas** [comment]
Found it: 
https://www.gibberlings3.net/forums/topic/27535-making-mods-10-party-members-aware-draft/

**Comment by lynxlynxlynx** [comment]
Thanks, updated.
